version: "2"

services:

  namenode:
    build: .
    image: alecspopa/giraph-cluster
    container_name: hdfs_namenode
    hostname: hdfs-namenode
    command: ["/etc/bootstrap.sh", "-namenode"]
    ports:
      - "50070:50070"

  secondarynamenode:
    image: alecspopa/giraph-cluster
    container_name: hdfs_secondarynamenode
    hostname: hdfs-secondarynamenode
    command: ["/etc/bootstrap.sh", "-secondarynamenode"]
    ports:
      - "50090:50090"
    links:
      - namenode:hdfs-namenode

  datanode:
    image: alecspopa/giraph-cluster
    command: ["/etc/bootstrap.sh", "-datanode"]
    ports:
      # The host port is randomly assigned by Docker, to allow scaling to multiple DataNodes on the same host
      - "50075"
    links:
      - namenode:hdfs-namenode

  yarn:
    image: alecspopa/giraph-cluster
    container_name: hdfs_yarn
    hostname: hdfs-yarn
    command: ["/etc/bootstrap.sh", "-yarn"]
    ports:
      - "8088:8088"
      - "8042:8042"
    links:
      - namenode:hdfs-namenode
      - datanode

  mrjobhistory:
    image: alecspopa/giraph-cluster
    container_name: hdfs_mrjobhistory
    hostname: hdfs-mrjobhistory
    command: ["/etc/bootstrap.sh", "-mrjobhistory"]
    ports:
      - "10020:10020"
      - "19888:19888"
    links:
      - namenode:hdfs-namenode
      - datanode
